### ISSUE TITLE
Don't collect green coins

### ISSUE THREAD

**Issue by whiitees** [Wokzy/blum-bot#12]
Hi, whaen I write python main.py
And press "play" on Blum it doens't collect any green coins.
Trying to detect running game, click play
Error:
Traceback (most recent call last):
  File "D:\BOT\blum-bot-master\blum-bot-master\main.py", line 125, in <module>
    main()
  File "D:\BOT\blum-bot-master\blum-bot-master\main.py", line 80, in main
    wait_running_game(camera)
  File "D:\BOT\blum-bot-master\blum-bot-master\main.py", line 60, in wait_running_game
    application_bbox = prepare_app()
                       ^^^^^^^^^^^^^
  File "D:\BOT\blum-bot-master\blum-bot-master\prepare_app.py", line 23, in prepare_app
    win32gui.SetForegroundWindow(hwnd)
pywintypes.error: (0, 'SetForegroundWindow', 'No error message is available')

**Comment by Wokzy** [comment]
Hello. Seems like smth wrong with windows api not with my script. Try to rerun `main.py` several times, run it after pressing `play`

**Comment by rezamusic7** [comment]
It is working very well but sometimes hit bombs.
