### ISSUE TITLE
OSError: [WinError 87] The parameter is incorrect.

### ISSUE THREAD

**Issue by hhjoo** [Wokzy/blum-bot#23]
I face this problem with python 3.10 and python 3.11.5

**Comment by HARSHRAJ676** [comment]
python main.py --elections

use this command

**Comment by hhjoo** [comment]
I already did

**Comment by hhjoo** [comment]
Exception in thread DXCamera:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\dxcam\dxcam.py", line 162, in __capture
    set_periodic_timer(self.__timer_handle, period_ms)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\dxcam\util\timer.py", line 34, in set_periodic_timer
    raise ctypes.WinError()
OSError: [WinError 87] The parameter is incorrect.

**Comment by Wokzy** [comment]
Try to lunch on elder versions, for instance 3.10 or even 3.9. I have no issues on 3.10.5, however on 3.12.3 my script doesn't work

**Comment by hhjoo** [comment]
Same Error with python 3.10.5

**Comment by hhjoo** [comment]
I tried to install python3.8.5 and this happened 

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from prepare_app import prepare_app
  File "C:\Users\Administrator\Desktop\blum-bot-master\prepare_app.py", line 9, in <module>
    def prepare_app() -> tuple[int]:
TypeError: 'type' object is not subscriptable

**Comment by hhjoo** [comment]
The problem is with windows 19 servers
It's working fine in windows 2022
